spring:
  application:
    name: ecommerce-app
  profiles:
    active: default

promotions:
  discounts:
    PERCENTAGE_DISCOUNT: 20
    FLAT_DISCOUNT: 5
    BUY_ONE_GET_ONE: 1
    SEASONAL_DISCOUNT: 15